### ISSUE TITLE
Some Cuban authors missing from list

### ISSUE THREAD

**Issue by rgraucrespo** [ypriverol/cubastats#1]
[x] Eduardo Menendez-Proupin: https://scholar.google.com/citations?user=PF4yHIEAAAAJ&hl=en
Rabdel Ruiz-Salvador: https://scholar.google.com/citations?hl=en&user=ZeXKD0YAAAAJ
Luisa Marleny Rodriguez-Albelo: https://scholar.google.com/citations?user=jRMOOhEAAAAJ&hl=en
Neyvis Almora-Barrios: https://scholar.google.com/citations?user=D02cHaQAAAAJ&hl=en

**Comment by ypriverol** [comment]
All included!! Thanks @rgraucrespo
